// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwsjkkmeamlbidqwsxzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3c2pra21lYW1sYmlkcXdzeHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDUzNjAsImV4cCI6MjA1MTU4MTM2MH0.ZzqwBimmZ2-yuHRFLyW6MuEonp5GYbi_alCTVcQWoTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);